---
name: Bug report
title: '[BUG] '
labels: [ bug ]
assignees: octocat
description: Describe the bug in detail.
body:
  - type: markdown
    attributes:
      value: |
        ## Describe the bug
        A clear and concise description of what the bug is.